// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/cn/edu/sdu/JT808Server/protobuf/JT808ClientHeader.proto

package cn.edu.sdu.JT808Server.protobuf;

public final class ClientDataOnlyHeader {
  private ClientDataOnlyHeader() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtocolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.Protocol)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 protoType = 1;</code>
     */
    boolean hasProtoType();
    /**
     * <code>required int32 protoType = 1;</code>
     */
    int getProtoType();

    /**
     * <code>optional string terminalPhone = 2;</code>
     */
    boolean hasTerminalPhone();
    /**
     * <code>optional string terminalPhone = 2;</code>
     */
    java.lang.String getTerminalPhone();
    /**
     * <code>optional string terminalPhone = 2;</code>
     */
    com.google.protobuf.ByteString
        getTerminalPhoneBytes();
  }
  /**
   * Protobuf type {@code protobuf.Protocol}
   */
  public  static final class Protocol extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.Protocol)
      ProtocolOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Protocol.newBuilder() to construct.
    private Protocol(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Protocol() {
      terminalPhone_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Protocol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              protoType_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              terminalPhone_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.internal_static_protobuf_Protocol_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.internal_static_protobuf_Protocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol.class, cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol.Builder.class);
    }

    private int bitField0_;
    public static final int PROTOTYPE_FIELD_NUMBER = 1;
    private int protoType_;
    /**
     * <code>required int32 protoType = 1;</code>
     */
    public boolean hasProtoType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 protoType = 1;</code>
     */
    public int getProtoType() {
      return protoType_;
    }

    public static final int TERMINALPHONE_FIELD_NUMBER = 2;
    private volatile java.lang.Object terminalPhone_;
    /**
     * <code>optional string terminalPhone = 2;</code>
     */
    public boolean hasTerminalPhone() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string terminalPhone = 2;</code>
     */
    public java.lang.String getTerminalPhone() {
      java.lang.Object ref = terminalPhone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          terminalPhone_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string terminalPhone = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTerminalPhoneBytes() {
      java.lang.Object ref = terminalPhone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        terminalPhone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasProtoType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, protoType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, terminalPhone_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, protoType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, terminalPhone_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol)) {
        return super.equals(obj);
      }
      cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol other = (cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol) obj;

      if (hasProtoType() != other.hasProtoType()) return false;
      if (hasProtoType()) {
        if (getProtoType()
            != other.getProtoType()) return false;
      }
      if (hasTerminalPhone() != other.hasTerminalPhone()) return false;
      if (hasTerminalPhone()) {
        if (!getTerminalPhone()
            .equals(other.getTerminalPhone())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasProtoType()) {
        hash = (37 * hash) + PROTOTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getProtoType();
      }
      if (hasTerminalPhone()) {
        hash = (37 * hash) + TERMINALPHONE_FIELD_NUMBER;
        hash = (53 * hash) + getTerminalPhone().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Protocol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.Protocol)
        cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.ProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.internal_static_protobuf_Protocol_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.internal_static_protobuf_Protocol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol.class, cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol.Builder.class);
      }

      // Construct using cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        protoType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        terminalPhone_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.internal_static_protobuf_Protocol_descriptor;
      }

      @java.lang.Override
      public cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol getDefaultInstanceForType() {
        return cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol.getDefaultInstance();
      }

      @java.lang.Override
      public cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol build() {
        cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol buildPartial() {
        cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol result = new cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.protoType_ = protoType_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.terminalPhone_ = terminalPhone_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol) {
          return mergeFrom((cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol other) {
        if (other == cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol.getDefaultInstance()) return this;
        if (other.hasProtoType()) {
          setProtoType(other.getProtoType());
        }
        if (other.hasTerminalPhone()) {
          bitField0_ |= 0x00000002;
          terminalPhone_ = other.terminalPhone_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasProtoType()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int protoType_ ;
      /**
       * <code>required int32 protoType = 1;</code>
       */
      public boolean hasProtoType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 protoType = 1;</code>
       */
      public int getProtoType() {
        return protoType_;
      }
      /**
       * <code>required int32 protoType = 1;</code>
       */
      public Builder setProtoType(int value) {
        bitField0_ |= 0x00000001;
        protoType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 protoType = 1;</code>
       */
      public Builder clearProtoType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        protoType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object terminalPhone_ = "";
      /**
       * <code>optional string terminalPhone = 2;</code>
       */
      public boolean hasTerminalPhone() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string terminalPhone = 2;</code>
       */
      public java.lang.String getTerminalPhone() {
        java.lang.Object ref = terminalPhone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            terminalPhone_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string terminalPhone = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTerminalPhoneBytes() {
        java.lang.Object ref = terminalPhone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          terminalPhone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string terminalPhone = 2;</code>
       */
      public Builder setTerminalPhone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        terminalPhone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string terminalPhone = 2;</code>
       */
      public Builder clearTerminalPhone() {
        bitField0_ = (bitField0_ & ~0x00000002);
        terminalPhone_ = getDefaultInstance().getTerminalPhone();
        onChanged();
        return this;
      }
      /**
       * <code>optional string terminalPhone = 2;</code>
       */
      public Builder setTerminalPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        terminalPhone_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.Protocol)
    }

    // @@protoc_insertion_point(class_scope:protobuf.Protocol)
    private static final cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol();
    }

    public static cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Protocol>
        PARSER = new com.google.protobuf.AbstractParser<Protocol>() {
      @java.lang.Override
      public Protocol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Protocol(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Protocol> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Protocol> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.edu.sdu.JT808Server.protobuf.ClientDataOnlyHeader.Protocol getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Protocol_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Protocol_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nEsrc/main/java/cn/edu/sdu/JT808Server/p" +
      "rotobuf/JT808ClientHeader.proto\022\010protobu" +
      "f\"4\n\010Protocol\022\021\n\tprotoType\030\001 \002(\005\022\025\n\rterm" +
      "inalPhone\030\002 \001(\tB9\n\037cn.edu.sdu.JT808Serve" +
      "r.protobufB\024ClientDataOnlyHeaderH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_Protocol_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_Protocol_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Protocol_descriptor,
        new java.lang.String[] { "ProtoType", "TerminalPhone", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
